In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
#import plotly.express as px

ImportError: No module named plotly.express

In [2]:
data = pd.read_csv('confirmed_cases_world_wide_who.csv')
data.head()

,Date,China,Hong Kong,Macau,Taipei,Japan,South Korea,Viet Nam,Singapore,Australia,...,France,Finland,Germany,Italy,Russia,Spain,Sweden,UK,Belgium,UAE
0,1/21/2020,278,0,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1/22/2020,309,0,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1/23/2020,568,1,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1/24/2020,825,2,2,1,1,2,2,1,0,...,0,0,0,0,0,0,0,0,0,0
4,1/25/2020,1287,5,2,3,3,2,2,3,3,...,3,0,0,0,0,0,0,0,0,0

In [ ]:
# plot the carona virus in china vs day
# plot the bar plot the avg of the all countries visus results